---
- name: Install packages using package manager
  hosts: localhost
  connection: local
  become: yes
  vars:
    nvm_version: "0.40.1"
    node_version: "lts/*"
  tasks:
    - name: Import VirtualBox GPG key
      rpm_key:
        key: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add VirtualBox repository
      get_url:
        url: https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
        dest: /etc/yum.repos.d/virtualbox.repo
        mode: '0644'
    - name: Import VSCodium GPG key
      rpm_key:
        key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
        state: present

    - name: Add VSCodium repository
      yum_repository:
        name: gitlab.com_paulcarroty_vscodium_repo
        description: VSCodium repository
        baseurl: https://download.vscodium.com/rpms/
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
        metadata_expire: 1h

    - name: Update package cache
      dnf:
        update_cache: yes
      when: ansible_pkg_mgr == 'dnf'

    - name: Update all packages
      dnf:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == 'dnf'

    - name: Install packages
      package:
        name:
          - krb5-workstation
          - jq
          - ansible
          - fwupd
          - smartmontools
          - chntpw
          - genisoimage
          - aria2
          - net-tools
          - wireguard-tools
          - VirtualBox-7.1
          - chromium
          - libxdo
          - guake
          - git-lfs
          - codium
          - grub-customizer
          - openvpn
          - thunderbird
          - dnsmasq
          - firefox
          - keepassxc
          - flameshot
          - ripgrep
          - ufw
          - golang
          - shellcheck
        state: present

    - name: Install RPM Fusion free release (Fedora only)
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
        state: present
        disable_gpg_check: yes
      when: ansible_distribution == 'Fedora'

    - name: Download NVM installation script
      get_url:
        url: "https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh"
        dest: /tmp/nvm_install.sh
        mode: '0755'
      become: no
    - name: Install NVM
      shell: /tmp/nvm_install.sh
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      become: no

    - name: Source NVM in .bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "[ -s '$HOME/.nvm/nvm.sh' ] && \\. '$HOME/.nvm/nvm.sh'"
        state: present
      become: no

    - name: Install latest LTS Node.js and npm
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install {{ node_version }}
        nvm use {{ node_version }}
      args:
        executable: /bin/bash
      become: no

    - name: Install global npm packages
      npm:
        name: "{{ item }}"
        global: yes
      loop:
        - "@bitwarden/cli"
        - "@angular/cli"
      become: no
      environment:
        PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/{{ node_version }}/bin:{{ ansible_env.PATH }}"

