---
- name: Install packages using package manager
  hosts: localhost
  connection: local
  become: yes
  vars:
    nvm_version: "0.40.1"
    node_version: "lts/*"
  tasks:
    - name: Install packages
      package:
        name:
          - krb5-workstation
          - jq
          - ansible
          - fwupd
          - smartmontools
          - chntpw
          - genisoimage
          - aria2
          - net-tools
          - wireguard-tools
          - VirtuslBox
          - chromium
          - libxdo
          - guake
          - git-lfs
          - codium
          - grub-customizer
          - openvpn
          - thunderbird
          - dnsmasq
          - firefox
          - keepassxc
          - flameshot
          - ripgrep
          - ufw
          - golang
          - shellcheck
        state: present

    - name: Install RPM Fusion free release (Fedora only)
      dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
        state: present
        disable_gpg_check: yes
      when: ansible_distribution == 'Fedora'

    - name: Install ffmpeg-libs (allowing erasing)
      package:
        name: ffmpeg-libs
        state: present
      vars:
        ansible_dnf_install_args: --allowerasing
      when: ansible_pkg_mgr == 'dnf'

    - name: Download NVM installation script
      get_url:
        url: "https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh"
        dest: /tmp/nvm_install.sh
        mode: '0755'
      become: no
    - name: Install NVM
      shell: /tmp/nvm_install.sh
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      become: no

    - name: Source NVM in .bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "[ -s '$HOME/.nvm/nvm.sh' ] && \\. '$HOME/.nvm/nvm.sh'"
        state: present
      become: no

    - name: Install latest LTS Node.js and npm
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install {{ node_version }}
        nvm use {{ node_version }}
      args:
        executable: /bin/bash
      become: no

    - name: Install global npm packages
      npm:
        name: "{{ item }}"
        global: yes
      loop:
        - "@bitwarden/cli"
        - "@angular/cli"
      become: no
      environment:
        PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/{{ node_version }}/bin:{{ ansible_env.PATH }}"

